### ISSUE TITLE
runFQSCRN_6.bash consistently failing on one file

### ISSUE THREAD

**Issue by nerdbrained** [philippinespire/pire_fq_gz_processing#3]
Running on the Sob shotgun data in /home/e1garcia/shotgun_PIRE/pire_ssl_data_processing/sphyraena_obtusata- runFQSCRN_6.bash worked fine for 5/6 files but did not work for Sob-CKal_018_Ex2-9G-ssl_L2_clmp.fp2_r2.fq.gz. This file definitely exists and does not appear to be any different from the others. fqscreen begins processing file but then gives the following error messages in the .out:

```
Can't write temp subset file: Input/output error at /opt/conda/bin/fastq_screen line 1630, <IN_SUBSET> line 104174456.
Use of uninitialized value $readsprocessed in numeric eq (==) at /opt/conda/bin/fastq_screen line 456, <IN_SUBSET> line 104174456.
No reads in Sob-CKal_018_Ex2-9G-ssl_L2_clmp.fp2_r2.fq.gz, skipping
```

I went back and tried runFQSCRN_6.bash with Sob-CKal_018_Ex2-9G-ssl_L2_clmp.fp2_r2.fq.gz as the final argument to just run this file (which is the solution proposed in the readme), but have gotten the same identical error message three times.

Just wondering if this has happened to anyone else and how to resolve this type of error if it continues to occur...

Outfiles from runs that failed:
slurm-fqscrn.1113704.3.out
slurm-fqscrn.1113924.0.out
slurm-fqscrn.1113926.0.out
slurm-fqscrn.1113928.0.out

**Comment by cbird808** [comment]
I'd ask Min.

Fwiw, those file names don't fit the ddocent naming convention and will have issues at some point, but not fqscreen.

From: nerdbrained ***@***.***>
Sent: Wednesday, September 21, 2022 8:06 AM
To: philippinespire/pire_fq_gz_processing ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [philippinespire/pire_fq_gz_processing] runFQSCRN_6.bash consistently failing on one file (Issue #3)


Running on the Sob shotgun data - runFQSCRN_6.bash worked fine for 5/6 files but did not work for Sob-CKal_018_Ex2-9G-ssl_L2_clmp.fp2_r2.fq.gz. This file definitely exists and does not appear to be any different from the others. fqscreen begins processing file but then gives the following error messages in the .out:

Can't write temp subset file: Input/output error at /opt/conda/bin/fastq_screen line 1630, <IN_SUBSET> line 104174456.

Use of uninitialized value $readsprocessed in numeric eq (==) at /opt/conda/bin/fastq_screen line 456, <IN_SUBSET> line 104174456.

No reads in Sob-CKal_018_Ex2-9G-ssl_L2_clmp.fp2_r2.fq.gz, skipping

I went back and tried runFQSCRN_6.bash with Sob-CKal_018_Ex2-9G-ssl_L2_clmp.fp2_r2.fq.gz as the final argument to just run this file (which is the solution proposed in the readme), but have gotten the same identical error message three times.

Just wondering if this has happened to anyone else and how to resolve this type of error if it continues to occue...

-

**Comment by ericgarciaresearch** [comment]
Issue has been solved
