### ISSUE TITLE
MultiQC twice on Step 12

### ISSUE THREAD

**Issue by jbaldisimo** [philippinespire/pire_fq_gz_processing#6]
On Step 12, when we run the runREPAIR.sbatch script, it executes multiQC automatically and outputs an fqc_rprd_report.html file (along with plots, etc.). But the repo instructions say we should run MultiQC separately after: sbatch /home/e1garcia/shotgun_PIRE/pire_fq_gz_processing/Multi_FASTQC.sh "./fq_fp1_clmp_fp2_fqscrn_rprd" "fqc_rprd_...and so on

Do we need to run MultiQC again so that it's harnessed in the process_metadata? I saw that fqc_rprd_report_data folder is created that has various text files, so it seems MultiQC doesn't have to be run anymore and process_metadata information is already created.

@cbird808

**Comment by ericgarciaresearch** [comment]
MultiQC is not running in the Repair script anymore, it should be run separately after Repair
