### ISSUE TITLE
Update Step `9c. Check duplicate removal success`

### ISSUE THREAD

**Issue by kllabrador** [philippinespire/pire_fq_gz_processing#7]
(1)
The container that should be loaded to run R needs to be updated,

from 
`module load container_env mapdamage2`

to
`module load container_env R/4.2`

(2)
I also encountered a problem where `checkClumpify_EG.R` will fail with the following error:

```
Error in `mutate()`:
ℹ In argument: `successful = map_lgl(...)`.
Caused by error in `map_lgl()`:
ℹ In index: 197.
Caused by error in `file()`:
! cannot open the connection
Backtrace:
     ▆
  1. ├─... %>% pull(out_files)
  2. ├─dplyr::pull(., out_files)
  3. ├─dplyr::filter(., !successful)
  4. ├─dplyr::mutate(...)
  5. ├─dplyr:::mutate.data.frame(...)
  6. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
  7. │   ├─base::withCallingHandlers(...)
  8. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
  9. │     └─mask$eval_all_mutate(quo)
 10. │       └─dplyr (local) eval()
 11. ├─purrr::map_lgl(out_files, ~read_lines(.x) %>% str_detect("Done!") %>% any)
 12. │ └─purrr:::map_("logical", .x, .f, ..., .progress = .progress)
 13. │   ├─purrr:::with_indexed_errors(...)
 14. │   │ └─base::withCallingHandlers(...)
 15. │   ├─purrr:::call_with_cleanup(...)
 16. │   └─.f(.x[[i]], ...)
 17. │     ├─read_lines(.x) %>% str_detect("Done!") %>% any
 18. │     └─readr::read_lines(.x)
 19. │       └─vroom::vroom_lines(...)
 20. │         └─vroom:::vroom_(...)
 21. ├─stringr::str_detect(., "Done!")
 22. │ └─stringr:::check_lengths(string, pattern)
 23. │   └─vctrs::vec_size_common(...)
 24. ├─vroom (local) `<fn>`("fq_fp1_clmp_fp2")
 25. │ └─vroom:::detect_compression(path)
 26. │   └─base::readBin(path, "raw", n = 6)
 27. │     └─base::file(con, "rb")
 28. └─base::.handleSimpleError(...)
 29.   └─purrr (local) h(simpleError(msg, call))
 30.     └─cli::cli_abort(...)
 31.       └─rlang::abort(...)
Execution halted
```

What I did to remedy this was to change line 8 in `checkClumpify_EG.R`:

From
`failed_out_files <- list.files(pattern = 'clmp_') %>%`

To
`failed_out_files <- list.files(pattern = 'clmp_r') %>%`

(3) 
The changes I made are done on my home directory. I have not made any changes in the e1garcia repo yet. Give me the green light and I will push the changes.

**Comment by ericgarciaresearch** [comment]
You have the green light 👍 . Please move the "checkClumpify.R" and "checkClumpify_EG" to the deprecated dir, and make a new copy of the updated version in the fq_gz_processing  dir

**Comment by ericgarciaresearch** [comment]
You have the green light 👍 . Please move the "checkClumpify.R" and "checkClumpify_EG" to the deprecated dir, and make a new copy of the updated version in the fq_gz_processing  dir
